name: Code Analysis with Code Climate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Run Code Climate Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install codeclimate-cli

      - name: Run Code Climate analysis
        run: |
          codeclimate analyze --dev -f json > codeclimate.json

      - name: Upload Code Climate data
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }} 
        with:
           coverageCommand: 'cat codeclimate.json'
